### ISSUE TITLE
pre-mRNA option not working?

### ISSUE THREAD

**Issue by jmcalabr** [YeoLab/clipper#102]
Hello,

We are wondering if the --premRNA option has been depracated in the newest version of clipper?

Our installation of clipper works well when we do not use --premRNA option, but this command (or others like it) fail:
clipper -b tsc_B5_matrin3-rip_S14_R1_001_Aligned.sorted.out.bam -o matrin3_clipper_mm9p.bed -s mm9 --premRNA

Thank you
Mauro Calabrese (UNC Chapel Hill)

**Comment by byee4** [comment]
Yes I believe that option is deprecated for the time being.
