### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ecwheele** [YeoLab/clipper#31]
git clone worked fine.

python setup.py install gives the following error: 

https://gist.github.com/ecwheele/400efcf19128b9933ea9

**Comment by gpratt** [comment]
What version of python are you using?

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by ecwheele** [comment]
That was python3. Went back to python2 and all is well in the world.
