### ISSUE TITLE
missing dependency :: gscripts 

### ISSUE THREAD

**Issue by EricDeveaud** [YeoLab/clipper#34]
clipper 1.1 installed via  "python setup.py install --prefix=XYZ"

running clip analysis ends with 

'''
ImportError: No module named gscripts.general.pybedtools_helpers
'''

**Comment by gpratt** [comment]
Thats for the info.  As a stopgap here is the package

https://github.com/YeoLab/gscripts.git

It should install.  Just fine after you download and install that repo.

**Comment by EricDeveaud** [comment]
clipper is documented as a dependency of FAST-iCLIP (https://github.com/ChangLab/FAST-iCLIP)

so I tried to install ONLY clipper, but clipper stand-alone (https://github.com/YeoLab/clipper)  is broken du to the missing gsscript dependency.

**Comment by EricDeveaud** [comment]
funny part.

'''
wget https://github.com/YeoLab/gscripts/archive/1.1.tar.gz && tar xf 1.1.tar.gz
cd gscripts-1.1
python setup.py install
....//....
Searching for clipper==0.2.0
Best match: clipper 0.2.0
Processing clipper-0.2.0-py2.7-linux-x86_64.egg
Adding clipper 0.2.0 to easy-install.pth file
Installing clipper script to /local/gensoft2/adm/bin
Installing clip_analysis script to /local/gensoft2/adm/bin
'''

clipper depends on gsscripts wich depends on clipper ??

**Comment by gpratt** [comment]
We take the Microsoft style of programming here, bootstrapping and circular dependences.  

I've removed the dependency on gscripts. Checkout the latest master branch and it should work now.

**Comment by EricDeveaud** [comment]
works great. 

thanks !
