### ISSUE TITLE
inconsistent versionning :: release tag vs setup.py version

### ISSUE THREAD

**Issue by EricDeveaud** [YeoLab/clipper#35]
release tarball version is 1.1
setup.py claims to be 0.2.0 

same as problem as #25

**Comment by gpratt** [comment]
Unless its breaking something for you I'll fix this in the next major release.  We don't have a very good toolchain for updating version numbers.

**Comment by EricDeveaud** [comment]
it is not nreaking things, but our policy is to use release as much as
possible instead of git clone.

in order to have some reproductibilities tracking.

no worries for updating this. just kee it in mind for hte next release ;-)

regards

Eric

2016-04-06 18:54 GMT+02:00 Gabriel Pratt <notifications@github.com>:

**Comment by algaebrown** [comment]
Fixed in clipper 2.0.0
