### ISSUE TITLE
Clipper fails to build spline

### ISSUE THREAD

**Issue by ShanSabri** [YeoLab/clipper#42]
```
ssabri@n7131 2016-08-12]$ clipper -b BAMs/AGA.trimmed.uniq.sort.bam -s mm9 --premRNA --bonferroni --outfile peaks/AGA.trimmed.uniq.bed
ERROR:root:failed to build spline (m>k) failed for hidden m: fpcurf0:m=2, [0 1], [ 27.   0.], 11, 3, None
ERROR:root:peak finding failed:, ENSMUSG00000039801.6, (m>k) failed for hidden m: fpcurf0:m=2
Process PoolWorker-10:
Traceback (most recent call last):
  File "/u/local/apps/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/u/local/apps/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/u/local/apps/python/2.7.3/lib/python2.7/multiprocessing/pool.py", line 99, in worker
    put((job, i, result))
  File "/u/local/apps/python/2.7.3/lib/python2.7/multiprocessing/queues.py", line 390, in put
    return send(obj)
PicklingError: Can't pickle <class 'dfitpack.error'>: import of module dfitpack failed

```

If I do not escape the command the following warning message shows: 

```
WARNING:py.warnings:/u/local/apps/python/2.7.3/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py:208: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)

```

**Comment by ShanSabri** [comment]
Using the `--algorithm=classic` argument gives: 

```
[ssabri@n7131 2016-08-12]$ clipper -b BAMs/AGA.trimmed.uniq.sort.bam -s mm9 --premRNA --bonferroni --algorithm=classic --outfile peaks/AGA.trimmed.uniq.bed
ERROR:root:peak finding failed:, ENSMUSG00000064340.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064339.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064353.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064352.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064337.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064360.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064358.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064354.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064366.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064351.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064341.1, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000056673.7, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000064356.3, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000069049.5, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000069053.5, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000065947.3, peaks() takes exactly 2 arguments (1 given)
ERROR:root:peak finding failed:, ENSMUSG00000053211.4, peaks() takes exactly 2 arguments (1 given)
...
...
```

using `algorithm=gaussian` gives: 

```
[ssabri@n7131 2016-08-12]$ clipper -b BAMs/AGA.trimmed.uniq.sort.bam -s mm9 --premRNA --bonferroni --algorithm=gaussian --outfile peaks/AGA.trimmed.uniq.bed
ERROR:root:peak finding failed:, ENSMUSG00000064340.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064339.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064352.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064353.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064358.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064360.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064337.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064354.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064366.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064356.3, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000056673.7, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064351.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000069049.5, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000064341.1, 'GaussMix' object has no attribute 'model'
ERROR:root:peak finding failed:, ENSMUSG00000069053.5, 'GaussMix' object has no attribute 'model'
...
...
```

Help would be much appreciated!

**Comment by ShanSabri** [comment]
Using the `--debug --verbose` flags in addition to `--algorithm=spline` gives:

```
[ssabri@n7131 2016-08-12]$ clipper -b BAMs/AGA.trimmed.uniq.sort.bam -s mm9 --premRNA --bonferroni --algorithm=spline --debug --verbose --outfile peaks/AGA.trimmed.uniq.bed
ERROR:root:failed to build spline (m>k) failed for hidden m: fpcurf0:m=2, [0 1], [ 27.   0.], 11, 3, None
ERROR:root:peak finding failed:, ENSMUSG00000039801.6, (m>k) failed for hidden m: fpcurf0:m=2
Traceback (most recent call last):
  File "/u/local/apps/python/2.7.3/bin/clipper", line 9, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 674, in call_main
    main(options)
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 576, in main
    jobs.append(func_star(job))
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 146, in func_star
    return call_peaks(*varables)
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/call_peak.py", line 1100, in call_peaks
    raise error
dfitpack.error: (m>k) failed for hidden m: fpcurf0:m=2
```

**Comment by gpratt** [comment]
Man, I need to remove some of the experimental half working options...

I use these arguments

clipper  '-b'
'/projects/ps-yeolab3/encode/analysis/encode_v13/F7_IP_mnCLIP_IgG_high_1_hnRNPA2B1.merged.r2.bam'
'-s' 'hg19'  '-o'
'/projects/ps-yeolab3/encode/analysis/encode_v13/F7_IP_mnCLIP_IgG_high_1_hnRNPA2B1.merged.r2.peaks.bed'
'--bonferroni'  '--superlocal'  '--threshold-method' 'binomial'

Let me know if that works for you!

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by ShanSabri** [comment]
`clipper -b BAMs/AGA.trimmed.uniq.sort.bam -s mm9 --premRNA --bonferroni --superlocal --threshold-method=binomial --debug --verbose --outfile peaks/AGA.trimmed.uniq.bed` gave the same error as above: 

```
[ssabri@n7131 2016-08-12]$ clipper -b BAMs/AGA.trimmed.uniq.sort.bam -s mm9 --premRNA --bonferroni --superlocal --threshold-method=binomial --debug --verbose --outfile peaks/AGA.trimmed.uniq.bed
ERROR:root:failed to build spline (m>k) failed for hidden m: fpcurf0:m=2, [0 1], [ 27.   0.], 11, 3, None
ERROR:root:peak finding failed:, ENSMUSG00000039801.6, (m>k) failed for hidden m: fpcurf0:m=2
Traceback (most recent call last):
  File "/u/local/apps/python/2.7.3/bin/clipper", line 9, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 674, in call_main
    main(options)
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 576, in main
    jobs.append(func_star(job))
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 146, in func_star
    return call_peaks(*varables)
  File "/u/home/s/ssabri/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/call_peak.py", line 1100, in call_peaks
    raise error
dfitpack.error: (m>k) failed for hidden m: fpcurf0:m=2

```

**Comment by gpratt** [comment]
Thanks for all the info!  I guess at some point I should try to fix these smoothing issues.  

What version of clipper are you using?  The master version from github?  I'm not recognizing this error.

**Comment by ShanSabri** [comment]
$ pip freeze | grep 'clipper'
**clipper==0.2.0**

**Comment by gpratt** [comment]
Well thats annoying.

What are your versions of scipy and numpy?

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by ShanSabri** [comment]
I haven't upgraded Numpy or Scipy since my previous posts above (Numpy version 1.9.1 and Scipy version 0.15.1).

**Comment by j-pater** [comment]
Hello,

I am trying to use clipper on a mouse dataset with the command:
`clipper -b MB_150_A.Aligned.sortedByCoord.out.uniq.newCHR.bam -s mm10 -o 20_clipper_test_single.bed --FDR=0.001 --poisson-cutoff 1 --disable_global_cutoff --max_gap=20 --premRNA --bonferroni --threshold-method=binomial`

and I'm getting the same error reported in the first post of this thread:

`ERROR:root:failed to build spline (m>k) failed for hidden m: fpcurf0:m=3, [0 1 2], [ 36.  36.   0.], 11, 3, None
ERROR:root:peak finding failed:, ENSMUSG00000046201, (m>k) failed for hidden m: fpcurf0:m=3
Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 99, in worker
    put((job, i, result))
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 390, in put
    return send(obj)
PicklingError: Can't pickle <class 'dfitpack.error'>: import of module dfitpack failed`

The version of SciPy: **0.18.0**
The version of NumPy: **1.11.1**

Is this because I'm using _experimental_ options?

Thank you for your help.

**Comment by ShanSabri** [comment]
I return the same error using the following params: 

```
[ssabri@n2188 chr1]$ clipper -b AGA.trimmed.uniq.MAPPED.chr1.sort.bam -s mm9 --premRNA --bonferroni --outfile AGA.trimmed.uniq.MAPPED.chr1.sort.bed
ERROR:root:failed to build spline (m>k) failed for hidden m: fpcurf0:m=3, [0 1 2], [ 4.  4.  0.], 11, 3, None
ERROR:root:peak finding failed:, ENSMUSG00000073664.4, (m>k) failed for hidden m: fpcurf0:m=3
Process PoolWorker-5:
Traceback (most recent call last):
  File "/u/local/apps/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/u/local/apps/python/2.7.3/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/u/local/apps/python/2.7.3/lib/python2.7/multiprocessing/pool.py", line 99, in worker
    put((job, i, result))
  File "/u/local/apps/python/2.7.3/lib/python2.7/multiprocessing/queues.py", line 390, in put
    return send(obj)
PicklingError: Can't pickle <class 'dfitpack.error'>: import of module dfitpack failed

```

If the error is not being fixed, then is there a way around it?

**Comment by gpratt** [comment]
hmm... let me keep digging into this.  I'm at a bit of a loss, can't easily
repo the bug, and don't know whats causing it.  All your versions look
correct.



Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by gpratt** [comment]
oh wait, reading over your log again.  It looks like you're using the
version from pip?  Thats very out of date.  Please use the master branch on
github.  See if that fixes things.

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by gpratt** [comment]
If you can somehow share the bam with me, I'll try to repo your error on my cluster.  I strongly suspect its an issue with some installed packages, but always worth double checking.

**Comment by sridhar0605** [comment]
I ran in to this issue (cloned master from github)
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/bin/clipper", line 11, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/home/sridnona/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 688, in call_main
    main(options)
  File "/home/sridnona/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 584, in main
    jobs.append(func_star(job))
  File "/home/sridnona/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 147, in func_star
    return call_peaks(*varables)
  File "/home/sridnona/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/call_peak.py", line 1047, in call_peaks
    plot_sections(wiggle, sections, premRNA_threshold)
  File "/home/sridnona/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/call_peak.py", line 789, in plot_sections
    fig = plt.figure()
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/opt/rh/python27/root/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1764, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable


Also I am not able to run it in parallel end up with this error
clipper -b r2_sorted.bam -s hg19 -o r2_sorted_1.bed --superlocal --save-pickle --processors 10
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/bin/clipper", line 11, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/home/sridnona/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 688, in cal                                      l_main
    main(options)
  File "/home/sridnona/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 590, in mai                                      n
    with multiprocessing.Pool(int(options.np)) as pool:
AttributeError: __exit__

**Comment by gpratt** [comment]
hmm... That error shouldn't happen, and I've never run into it.

Maybe try to run the encode branch?  Its more up to date?

https://github.com/YeoLab/clipper/tree/encode_branch



Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by nattifftoffe** [comment]
Hi,
I'm running in the "failed to build spline" issue from the original comment. I am using the latest version from the encode branch though. Is there something I'm missing?

clipper -b input.bam -s hg19 -o output.bed --processors=8

**Comment by gpratt** [comment]
Are you running an outdated version of scipy / numpy?  

I don't see anything obvious thats going wrong.

**Comment by nattifftoffe** [comment]
Thanks for the quick response. My versions are the latest ones(to my knowledge):
>>> scipy.__version__
'0.18.1'
>>> numpy.__version__
'1.12.0'

**Comment by j-pater** [comment]
Hello,

I am not sure this has been mentioned or is implicit in the error message, but I would like to share an explanation to the error. In fact, this happens when in a given section of a gene, the number of data points the program is trying to fit a spline to is inferior or equal to the degree of such spline (m<=k, k= 3 by default). A way around this is to modify the code in the <code>call_peaks()</code> function of the <code>call_peak.py</code> module, right after the instantiation of the <code>SmoothingSpline</code> object (block starting at line 1091), by verifying that the m>k condition is fulfilled and decreasing the spline degree otherwise:

```
while fitter.k >= len(xvals):
    fitter.k = len(xvals) – 1
```

However, I ignore how this change impacts the quality of the peak detection for sections in which m<=k happens, given the warning message returned by the program (and already mentioned above):

```
WARNING:py.warnings:/usr/local/lib/python2.7/dist-packages/scipy/interpolate/fitpack2.py:222: UserWarning:
The maximal number of iterations maxit (set to 20 by the program) 
allowed for finding a smoothing spline with fp=s has been reached: s 
too small.
There is an approximation returned but the corresponding weighted sum 
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
    warnings.warn(message)
```

I would like to read your opinion on this. Is it better to decrease the spline degree or should we try to find a way to filter out these sections before trying to fit a spline to the data points?

Cheers.

**Comment by algaebrown** [comment]
https://github.com/YeoLab/clipper/releases/tag/2.0
fixed in new python 3 based CLIPper
