### ISSUE TITLE
AttributeError: __exit__

### ISSUE THREAD

**Issue by noncodo** [YeoLab/clipper#49]
Trying to run clipper, I get the following error: 

`clipper  -b R3_STAR.bam.srtd -s hg19 -o test.bed --processors=4
`
Traceback (most recent call last):
  File "/Users/me/miniconda2/bin/clipper", line 9, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/Users/me/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-macosx-10.6-x86_64.egg/clipper/src/peakfinder.py", line 688, in call_main
    main(options)
  File "/Users/me/.local/lib/python2.7/site-packages/clipper-0.2.0-py2.7-macosx-10.6-x86_64.egg/clipper/src/peakfinder.py", line 590, in main
    with multiprocessing.Pool(int(options.np)) as pool:
AttributeError: __exit__

**Comment by noncodo** [comment]
Ahha, it could be that this error is simply due to the fact that I am using "-s hg19" while my bam file is mapped to hg38. 
Would it be possible to catch this error and throw a warning to the user?

**Comment by PaulAdrian89** [comment]
Exact same problem here. In my case it's not beacause of hg version differences.

**Comment by PaulAdrian89** [comment]
So, I found something that worked for me.
I changed the following lines from the peakfinder.py file and it was fine:
From the original:
589 else:
590        with multiprocessing.Pool(int(options.np)) as pool:
591            jobs = [pool.apply_async(call_peaks, job) for job in tasks]
 
Changed to:
589  else:
590        pool = multiprocessing.Pool(int(options.np))
591        jobs = [pool.apply_async(call_peaks, job) for job in tasks]

**Comment by Psy-Fer** [comment]
Alternatively, you should be able to use contextlib and closing()

The with statement on  multithreading only works in python 3.3 or higher.

So you should be able to go
from contextlib import closing

with closing(multiprocessing.Pool(int(options.np)) as pool:
    jobs = [pool.apply_async(call_peaks, job) for job in tasks]
...
...
    Pool.terminate()

Should maintain the code as is a bit closer

**Comment by noncodo** [comment]
Yes this works, although I got some funky error related issues. uncommenting the following error reporting line fixed it.
