### ISSUE TITLE
installation issues. 

### ISSUE THREAD

**Issue by akdess** [YeoLab/clipper#53]
I tried installing clipper using python3.5. I get the following error. Do you have any idea why? 

clipper/src/peaksmodule.cc: In function 'int main(int, char**)':
clipper/src/peaksmodule.cc:26:28: error: cannot convert 'char*' to 'wchar_t*' for argument '1' to 'void Py_SetProgramName(wchar_t*)'
   Py_SetProgramName(argv[0]);
                            ^
clipper/src/peaksmodule.cc: In function 'PyObject* peaks_shuffle(PyObject*, PyObject*)':
clipper/src/peaksmodule.cc:86:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for( int i = 0; i < HEIGHT.size(); i++) {
                                     ^
clipper/src/peaksmodule.cc:92:55: error: 'PyInt_AsLong' was not declared in this scope
       long len = PyInt_AsLong(PyList_GetItem(reads, i));
                                                       ^
clipper/src/peaksmodule.cc:123:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (GENE[j] >= HEIGHT.size()) { 
                                  ^
clipper/src/peaksmodule.cc:193:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (height_cutoff > OBS_CUTOFF.size()) {
                                         ^
clipper/src/peaksmodule.cc:202:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int cut = 0; cut < OBS_CUTOFF.size(); cut++) {
                                           ^
clipper/src/peaksmodule.cc:203:67: error: 'PyInt_FromLong' was not declared in this scope
     PyList_SetItem(returnList, cut, PyInt_FromLong(OBS_CUTOFF[cut]));
                                                                   ^
clipper/src/peaksmodule.cc: In function 'PyObject* peaks_find_sections(PyObject*, PyObject*)':
clipper/src/peaksmodule.cc:261:51: error: 'PyInt_FromLong' was not declared in this scope
   PyTuple_SetItem(section, 0, PyInt_FromLong(start));
                                                   ^
clipper/src/peaksmodule.cc:271:53: error: 'PyInt_FromLong' was not declared in this scope
     PyTuple_SetItem(section, 0, PyInt_FromLong(start));
                                                     ^
clipper/src/peaksmodule.cc:281:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < sections.size(); i++) {
                                     ^
clipper/src/peaksmodule.cc: In function 'PyObject* peaks_readsToWiggle_pysam(PyObject*, PyObject*)':
clipper/src/peaksmodule.cc:329:37: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
   while (item = PyIter_Next(iterator)) {
                                     ^
clipper/src/peaksmodule.cc:390:59: error: 'PyInt_FromLong' was not declared in this scope
     PyTuple_SetItem(read_loc, 0, PyInt_FromLong(read_start));
                                                           ^
clipper/src/peaksmodule.cc:421:46: error: 'PyInt_AsLong' was not declared in this scope
      long incremented = PyInt_AsLong(jxnCount);
                                              ^
clipper/src/peaksmodule.cc:455:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < lengths.size(); i++) {
                                    ^
clipper/src/peaksmodule.cc:456:60: error: 'PyInt_FromLong' was not declared in this scope
     PyList_SetItem(retLengths, i, PyInt_FromLong(lengths[i]));
                                                            ^
clipper/src/peaksmodule.cc:464:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < wiggle.size(); i++) {
                                   ^
clipper/src/peaksmodule.cc:468:60: error: 'PyInt_FromLong' was not declared in this scope
       PyList_SetItem(retWiggle, i, PyInt_FromLong(wiggle[i]));
                                                            ^
clipper/src/peaksmodule.cc:471:66: error: 'PyInt_FromLong' was not declared in this scope
     PyList_SetItem(retPos_counts, i, PyInt_FromLong(pos_counts[i]));
                                                                  ^
clipper/src/peaksmodule.cc: In function 'PyObject* initpeaks()':
clipper/src/peaksmodule.cc:501:39: error: 'Py_InitModule' was not declared in this scope
   Py_InitModule("peaks", peaks_methods);
                                       ^
clipper/src/peaksmodule.cc:502:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
error: command 'gcc' failed with exit status 1

**Comment by wilzbach** [comment]
clipper simply doesn't support any Python3 version.
