### ISSUE TITLE
clipper won't run with bacterial genome

### ISSUE THREAD

**Issue by TsviyaOlender** [YeoLab/clipper#63]
Hi
I am trying to run Clipper on bacterial Clip-Seq data. I tried:
[lvzvia@molgen Sarit_Tsviya]$ python /home/labs/olenderlab/lvzvia/MySoftware/clipper-master/clipper/src/peakfinder.py -b alignment/m6A_2_10_AB_S8.U.bam --customBED genomeT/m6A_2_10_AB_S8.peaks.bed
Usage:
python peakfinder.py -b <bamfile> -s <hg18/hg19/mm9>
 OR

python peakfinder.py -b <bamfile> --customBED <BEDfile> --customMRNA
    <mRNA lengths> --customPREMRNA <premRNA lengths>

peakfinder.py: error: no such option: --customBED

so I have tried:
[lvzvia@molgen Sarit_Tsviya]$ python /home/labs/olenderlab/lvzvia/MySoftware/clipper-master/clipper/src/peakfinder.py -b alignment/m6A_2_10_AB_S8.U.bam --bedFile genomeT/m6A_2_10_AB_S8.peaks.bed
Usage:
python peakfinder.py -b <bamfile> -s <hg18/hg19/mm9>
 OR

python peakfinder.py -b <bamfile> --customBED <BEDfile> --customMRNA
    <mRNA lengths> --customPREMRNA <premRNA lengths>

peakfinder.py: error: no such option: --bedFile

and also
[lvzvia@molgen Sarit_Tsviya]$ clipper -b alignment/m6A_2_10_AB_S8.U.bam --bedFile genomeT/m6A_2_10_AB_S8.peaks.bed
Usage:
python peakfinder.py -b <bamfile> -s <hg18/hg19/mm9>
 OR

python peakfinder.py -b <bamfile> --customBED <BEDfile> --customMRNA
    <mRNA lengths> --customPREMRNA <premRNA lengths>

clipper: error: no such option: --bedFile

How should I use it?

Tsviya

**Comment by naturale0** [comment]
same problem here too.

**Comment by hari-yalamanchili** [comment]
Any update on this? same issue here as well... Thx.

**Comment by byee4** [comment]
See issue #39 for how to run with a custom genome.
