### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rekado** [YeoLab/clipper#65]
Python 2 [will not be maintained past 2020](https://pythonclock.org/).  Now that pybedtools is available for Python 3, would it be possible to upgrade Clipper to use Python 3 instead of 2?

**Comment by rekado** [comment]
Python 2 is now officially EOL.  Are there any plans for upgrading Clipper to Python 3?

**Comment by algaebrown** [comment]
https://github.com/YeoLab/clipper/releases/tag/2.0
Here

**Comment by rekado** [comment]
Excellent, thank you!

I noticed that at least one file still uses Python 2-style print syntax:

```
test/data/test_peakfinder.py", line 100
    print len(tested_tool)
```

**Comment by rekado** [comment]
FYI: the latest version of clipper is now available through GNU Guix (the reproducible package manager) as of Guix commit 92b34df789: `guix install clipper`.

**Comment by algaebrown** [comment]
@rekado  Thank you so much for making the available in GNU!! the remaining py2 file is removed.
