### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by lll16** [YeoLab/clipper#71]
--Hi
Error reporting during installation：

running install
running bdist_egg
running egg_info
writing clipper.egg-info/PKG-INFO
writing dependency_links to clipper.egg-info/dependency_links.txt
writing entry points to clipper.egg-info/entry_points.txt
writing requirements to clipper.egg-info/requires.txt
writing top-level names to clipper.egg-info/top_level.txt
writing manifest file 'clipper.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
skipping 'clipper/src/readsToWiggle.c' Cython extension (up-to-date)
building 'clipper.src.peaks' extension
gcc -pthread -B /home/lll/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lll/miniconda3/include/python3.7m -c clipper/src/peaksmodule.cc -o build/temp.linux-x86_64-3.7/clipper/src/peaksmodule.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
clipper/src/peaksmodule.cc: In function ‘int main(int, char**)’:
clipper/src/peaksmodule.cc:26:28: error: cannot convert ‘char*’ to ‘const wchar_t*’ for argument ‘1’ to ‘void Py_SetProgramName(const wchar_t*)’
   Py_SetProgramName(argv[0]);
                            ^
clipper/src/peaksmodule.cc: In function ‘PyObject* peaks_shuffle(PyObject*, PyObject*)’:
clipper/src/peaksmodule.cc:86:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for( int i = 0; i < HEIGHT.size(); i++) {
                     ~~^~~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:92:18: error: ‘PyInt_AsLong’ was not declared in this scope
       long len = PyInt_AsLong(PyList_GetItem(reads, i));
                  ^~~~~~~~~~~~
clipper/src/peaksmodule.cc:92:18: note: suggested alternative: ‘PyLong_AsLong’
       long len = PyInt_AsLong(PyList_GetItem(reads, i));
                  ^~~~~~~~~~~~
                  PyLong_AsLong
clipper/src/peaksmodule.cc:123:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (GENE[j] >= HEIGHT.size()) {
clipper/src/peaksmodule.cc:193:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (height_cutoff > OBS_CUTOFF.size()) {
         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:202:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int cut = 0; cut < OBS_CUTOFF.size(); cut++) {
                     ~~~~^~~~~~~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:203:37: error: ‘PyInt_FromLong’ was not declared in this scope
     PyList_SetItem(returnList, cut, PyInt_FromLong(OBS_CUTOFF[cut]));
                                     ^~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:203:37: note: suggested alternative: ‘PyLong_FromLong’
     PyList_SetItem(returnList, cut, PyInt_FromLong(OBS_CUTOFF[cut]));
                                     ^~~~~~~~~~~~~~
                                     PyLong_FromLong
clipper/src/peaksmodule.cc: In function ‘PyObject* peaks_find_sections(PyObject*, PyObject*)’:
clipper/src/peaksmodule.cc:261:31: error: ‘PyInt_FromLong’ was not declared in this scope
   PyTuple_SetItem(section, 0, PyInt_FromLong(start));
                               ^~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:261:31: note: suggested alternative: ‘PyLong_FromLong’
   PyTuple_SetItem(section, 0, PyInt_FromLong(start));
                               ^~~~~~~~~~~~~~
                               PyLong_FromLong
clipper/src/peaksmodule.cc:271:33: error: ‘PyInt_FromLong’ was not declared in this scope
     PyTuple_SetItem(section, 0, PyInt_FromLong(start));
                                 ^~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:271:33: note: suggested alternative: ‘PyLong_FromLong’
     PyTuple_SetItem(section, 0, PyInt_FromLong(start));
                                 ^~~~~~~~~~~~~~
                                 PyLong_FromLong
clipper/src/peaksmodule.cc:281:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < sections.size(); i++) {
                   ~~^~~~~~~~~~~~~~~~~
clipper/src/peaksmodule.cc: In function ‘PyObject* peaks_readsToWiggle_pysam(PyObject*, PyObject*)’:
clipper/src/peaksmodule.cc:329:15: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
   while (item = PyIter_Next(iterator)) {
          ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:390:34: error: ‘PyInt_FromLong’ was not declared in this scope
     PyTuple_SetItem(read_loc, 0, PyInt_FromLong(read_start));
                                  ^~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:390:34: note: suggested alternative: ‘PyLong_FromLong’
     PyTuple_SetItem(read_loc, 0, PyInt_FromLong(read_start));
                                  ^~~~~~~~~~~~~~
                                  PyLong_FromLong
clipper/src/peaksmodule.cc:421:25: error: ‘PyInt_AsLong’ was not declared in this scope
      long incremented = PyInt_AsLong(jxnCount);
                         ^~~~~~~~~~~~
clipper/src/peaksmodule.cc:421:25: note: suggested alternative: ‘PyLong_AsLong’
      long incremented = PyInt_AsLong(jxnCount);
                         ^~~~~~~~~~~~
                         PyLong_AsLong
clipper/src/peaksmodule.cc:455:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < lengths.size(); i++) {
                   ~~^~~~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:456:35: error: ‘PyInt_FromLong’ was not declared in this scope
     PyList_SetItem(retLengths, i, PyInt_FromLong(lengths[i]));
                                   ^~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:456:35: note: suggested alternative: ‘PyLong_FromLong’
     PyList_SetItem(retLengths, i, PyInt_FromLong(lengths[i]));
                                   ^~~~~~~~~~~~~~
                                   PyLong_FromLong
clipper/src/peaksmodule.cc:464:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < wiggle.size(); i++) {
                   ~~^~~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:468:36: error: ‘PyInt_FromLong’ was not declared in this scope
       PyList_SetItem(retWiggle, i, PyInt_FromLong(wiggle[i]));
                                    ^~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:468:36: note: suggested alternative: ‘PyLong_FromLong’
       PyList_SetItem(retWiggle, i, PyInt_FromLong(wiggle[i]));
                                    ^~~~~~~~~~~~~~
                                    PyLong_FromLong
clipper/src/peaksmodule.cc:471:38: error: ‘PyInt_FromLong’ was not declared in this scope
     PyList_SetItem(retPos_counts, i, PyInt_FromLong(pos_counts[i]));
                                      ^~~~~~~~~~~~~~
clipper/src/peaksmodule.cc:471:38: note: suggested alternative: ‘PyLong_FromLong’
     PyList_SetItem(retPos_counts, i, PyInt_FromLong(pos_counts[i]));
                                      ^~~~~~~~~~~~~~
                                      PyLong_FromLong
clipper/src/peaksmodule.cc: In function ‘PyObject* initpeaks()’:
clipper/src/peaksmodule.cc:501:3: error: ‘Py_InitModule’ was not declared in this scope
   Py_InitModule("peaks", peaks_methods);
   ^~~~~~~~~~~~~
clipper/src/peaksmodule.cc:501:3: note: suggested alternative: ‘Py_Initialize’
   Py_InitModule("peaks", peaks_methods);
   ^~~~~~~~~~~~~
   Py_Initialize
clipper/src/peaksmodule.cc:502:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
error: command 'gcc' failed with exit status 1

how to fix that ?
Thank you！

**Comment by byee4** [comment]
Can you try installing Clipper with Python2.7?

**Comment by lll16** [comment]
running build_ext
building 'clipper.src.readsToWiggle' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/clipper
creating build/temp.linux-x86_64-2.7/clipper/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-MW0004/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c clipper/src/readsToWiggle.c -o build/temp.linux-x86_64-2.7/clipper/src/readsToWiggle.o
x86_64-linux-gnu-gcc: error: clipper/src/readsToWiggle.c: 没有那个文件或目录
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


Another error said the"clipper/src/readsToWiggle.c"not exist. What this file please? It doesn't contain in the folder I downloaded.

**Comment by algaebrown** [comment]
https://github.com/YeoLab/clipper/releases/tag/2.0
Installation error should be solved in new python 3 based CLIPper
