### ISSUE TITLE
About "--bonferroni -- superlocal"

### ISSUE THREAD

**Issue by Li-Yupeng** [YeoLab/clipper#77]
Hi,
    Some parameters such as "--bonferroni" and "-- superlocal" are described in the Wiki and the pipline (eCLIP-seq Processing Pipline v1.P 20160215). But they are not shown in "clipper -h" and reports erro when I call them.

**Comment by byee4** [comment]
I believe these are default now in the latest version: https://github.com/YeoLab/clipper/commit/77204cee6d3e7c73108724967063e4197845aa76
