### ISSUE TITLE
rmdup software

### ISSUE THREAD

**Issue by yx-xu** [YeoLab/clipper#81]
Hi !
     could you please recommend to me a software to remove PCR dupicate? And for all mapped reads and only uniquely mapped reads, which will be better to call peak? 
     Thank you very much!

**Comment by IrisWEI-1996** [comment]
Hi, I think there's a script that you can try for your eCLIP-seq analysis, it will remove the reads with the same UMI and chromosome location, and generate statistics table as well. The name of which is barcodecollapsepe.py, and link is here: https://github.com/YeoLab/eclip/blob/master/bin/barcodecollapsepe.py

- If you want to remove the reads based on the location, you can try samtools rmdup?

Hope this helps!

**Comment by byee4** [comment]
Hi, I suggest following the pipeline detailed [here](https://github.com/YeoLab/eclip).

For paired-end CLIP libraries generated via this protocol (https://pubmed.ncbi.nlm.nih.gov/27018577/) you may use the barcodecollapsepe script however make sure that each paired end is adjacent to each other (ie. namesorted BAM files).

For single-end CLIP libraries (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5991800/), please use [umi_tools](https://github.com/CGATOxford/UMI-tools) for extracting and de-duplicating reads.

**Comment by yx-xu** [comment]
Hi!
Thank you very much , IrisWEI-1996 and Brian Yee! Hope you happy all day~
