### ISSUE TITLE
Issue processing bam file (index out of error)

### ISSUE THREAD

**Issue by omarwagih** [YeoLab/clipper#96]
Hello, i'm trying to run clipper on an eCLIP experiment but I get the following index out of range error.

Is hg38 supported out of the box? I am using version 2.0.0

Link to data being processes:
https://www.ncbi.nlm.nih.gov/sra/?term=SRX7883128

Thanks!

```
~/clipper/hct116$ clipper -b HCT116_A2_1_WT_eCLIP_SRX7883128.bam -o out.bed -s hg38
{'bam': 'HCT116_A2_1_WT_eCLIP_SRX7883128.bam', 'species': 'hg38', 'outfileF': 'out.bed', 'gene': None, 'minreads': 3, 'poisson_cutoff': 0.05, 'use_global_cutoff': True, 'FDR_alpha': 0.05, 'binom': 0.05, 'threshold': None, 'maxgenes': None, 'np': 'autodetect', 'plotit': False, 'verbose': False, 'quiet': False, 'save_pickle': False, 'debug': False, 'max_gap': 15, 'timeout': None, 'premRNA': True, 'gtfFile': None, 'method': 'binomial', 'SloP': True, 'bonferroni_correct': True, 'algorithm': 'spline', 'reverse_strand': False, 'max_width': 75, 'min_width': 50}
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/omar/.conda/envs/clipper3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/omar/.conda/envs/clipper3/lib/python3.7/site-packages/clipper/src/call_peak.py", line 943, in call_peaks
    interval.stop, strand, "start", False)
  File "clipper/src/readsToWiggle.pyx", line 49, in clipper.src.readsToWiggle.readsToWiggle_pysam
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/omar/.conda/envs/clipper3/bin/clipper", line 8, in <module>
    sys.exit(call_main())
  File "/home/omar/.conda/envs/clipper3/lib/python3.7/site-packages/clipper/src/main.py", line 266, in call_main
    main(options)
  File "/home/omar/.conda/envs/clipper3/lib/python3.7/site-packages/clipper/src/main.py", line 105, in main
    peaks_dicts.append(job.get(timeout=options.timeout))
  File "/home/omar/.conda/envs/clipper3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range
```

**Comment by byee4** [comment]
Can you try using `--species GRCh38`?

**Comment by omarwagih** [comment]
Same issue. I tried processing one of the ENCODE eCLIP BAM files and it worked ok. 

Not sure how mine's any different. I'm using the pre-built hg38 reference/index from bowtie2.

**Comment by omarwagih** [comment]
So the bam file I have has additional scaffolds e.g. chr22_KI270737v1_random (see file below for full list) that do not exist in the internal database. Since I don't really care about these scaffolds, is there any quick way to get clipper to ignore those  chromosomes for the analysis instead of having to re-index and re-process all samples (I have a large number of samples so I would prefer avoiding doing that)

Thanks for your help!

[missing.txt](https://github.com/YeoLab/clipper/files/6542475/missing.txt)

**Comment by byee4** [comment]
I think you can probably extract only the reads from chromosomes you care about with samtools (see: https://www.biostars.org/p/302771/)

ie. 
`samtools view -b input.bam chr{1..22} > output.bam`

**Comment by omarwagih** [comment]
that worked for me, many thanks!
